version: '3.8'
services:
  php-apache-environment:
    build: .
    volumes:
      - ./server:/var/www/html
    ports:
      - 80:80
  angular-app:
    build: 
      context: ./
      dockerfile: docker/angular/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./src:/frontend/src